<%@page contentType="text/html" pageEncoding="UTF-8"%>

<%@include file="./includes/header.jsp" %>
<body>
    

    <h2 style="color:blue"<b>Terms & Conditions</b></h2>
<h3><b>ISPS TERMS AND CONDITIONS OF WEB SITE </b></h3>
<p>Please read all of the terms and conditions ("Terms") carefully before using this web site.</p>

<p><b>1. The Site.</b></p>
This web site (the "Site") is owned and provided by ISPS Corporation and its subsidiaries and affiliates ("ISPS") as a service to our customers and potential customers. Please feel free to browse this Site, but note that users of this Site ("you") are subject to these Terms and all applicable laws. If you disagree with these Terms, your exclusive remedy is to discontinue your use of this Site. ISPS may, at any time, edit or revise these Terms. JSP may also deny you access to this Site if you fail to comply with the Terms. All content on this Site may be changed, added, removed or updated at any time; however, JSP is under no obligation to do so.

<p><b>2. Uses of the Site.</p></b><!-- comment -->
The information on this Site is intended as a convenience and a service for ISPS customers and potential customers. You are not permitted to restrict or inhibit any other user from using or enjoying this Site. The copying, framing, mirroring, scraping or data-mining of this Site or any of its contents in any form or by any method is strictly prohibited. Access to this Site does not grant you any right, license or privilege to reproduce, publish or use any material on this Site or any property of JSP. Any ideas, concepts, techniques, procedures, methods, systems, designs, plans, charts or other materials you transmit to us through e-mail or this Site will become our property and may be used by us at any time and for any purpose, without restriction, unless otherwise agreed by ISPS.

<p><b>3. Disclaimers.</p></b><!-- comment -->
JSP will endeavor to ensure that the information supplied on this Site is true and accurate, however, JSP will not be responsible or liable for any inaccuracies. If inaccurate information is contained on this Site, please contact JSP. JSP makes no warranty that this Site is compatible with any computer systems or browsers and JSP cannot warrant that this Site is virus-free. THE SITE AND MATERIALS AND RELATED COMMUNICATIONS ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT ANY REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, ACCURACY, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR PARTICULAR PURPOSE.

<p><b>4. Limitation of Liability.</p></b><!-- comment -->
UNDER NO CIRCUMSTANCES WILL JSP OR OTHER RELATED OR THIRD PARTIES MENTIONED IN, OR INVOLVED IN CREATING, PRODUCING, OR DELIVERING THIS SITE BE LIABLE FOR ANY COMPENSATORY, DIRECT, INCIDENTAL, CONSEQUENTIAL, INDIRECT, SPECIAL OR PUNITIVE DAMAGES WHATSOEVER ARISING OUT OF YOUR ACCESS TO, USE OF, INABILITY TO USE OR THE MATERIALS OR THE CONTENT OF THIS SITE WHETHER BASED ON WARRANTY, CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER LEGAL THEORY, WHETHER OR NOT JSP WAS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. JSP SHALL HAVE NO LIABILITY OR RESPONSIBILITY FOR ANY ACTS, OMISSIONS OR CONDUCT OF ANY USER OR OTHER THIRD PARTY. Applicable laws of your jurisdiction may give you additional rights or may limit the effect of the waivers contained herein.

<p><b>5. Third-Party Sites.</p></b><!-- comment -->
As a convenience to you, JSP may provide links to web sites owned or operated by other entities and persons. If you use these web sites, you do so at your own risk. JSP make no warranties or representations regarding, and shall not be liable or responsible for, any linked web sites, your use of such sites, or the comprehensiveness or accuracy of information or materials appearing thereon or any products, publications, subject matter or services described thereon. Furthermore, links do not imply that JSP sponsors, endorses or is affiliated or associated with such sites, or that any linked web site is authorized to use any trademark, trade name, logo or copyright of JSP.

<p><b>6. Ownership and Copyright.</p></b><!-- comment -->
The trademarks, trade names and corporate logo displayed on this Site are the property of JSP Corporation and its subsidiaries and affiliates. The Site may contain information and materials including but not limited to, text, software, photos, video, graphics, audio, images or files incorporated in or generated by the software and data accompanying the software (collectively "Materials") which are derived in whole or in part from information and materials supplied by JSP and other sources, and are protected by U.S. and international copyright, trademark and other laws. The entire content of this Site is copyrighted as a collective work under the United States and other applicable copyright laws. JSP owns the copyright in the overall selection, coordination, arrangement and enhancement of such content, and owns the rights in (or license to use) the individual components of such content. Materials may not be modified, copied, reproduced, republished, modified, uploaded, posted, transmitted or distributed in any way or decompiled, reverse engineered or disassembled, except that you may view and print the Materials, provided you keep intact all copyright, trademark and other proprietary notices and make no change in or deletion of author attribution. This limited authorization is not a transfer of title in the Materials and you acknowledge that you do not acquire any license, ownership or other rights to the Materials or intellectual property. The use of any such Materials on any other web site without JSP's express written consent is prohibited.

<p><b>7. Miscellaneous.</p></b><!-- comment -->
These Terms constitute the entire agreement between ISPS and you with respect to your use of the Site.

</body>



<%@include file="./includes/footer.jsp" %>